services:
  mc-server:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      SERVER_NAME: "jax-server"
      EULA: TRUE
      TYPE: FABRIC
      VERSION: "1.21.10"
      LEVEL: "personal-survival"
      MODE: "survival"
      WHITELIST: |
        cojack
      OPS: |
        cojack
      INIT_MEMORY: "512M"
      MAX_MEMORY: "4G"
      USE_AIKAR_FLAGS: TRUE
    volumes:
      - /mc-server-data:/data
    restart: unless-stopped
